### PR TITLE
Fixed the code for running with python2.7 and python3.8

### PR DESCRIPTION
**Pull request by SchlegelS0208**
Hi Shaun,
I added various bugfixes and some sort of module handling for getting the import of Plugin to work (for python2.7 and python3.8 as well).

Currently I'm not able to upload the package into pypi.org , because I'm not allowed to.
Please get in touch with me (& the community), because we want to recycle your stuff. :-)

Cheers,
Steven

### CODE REVIEW

**Comment by bonesmoses** [comment]
Woah. People are still using this? I'm not very familiar with pypi to allow other people to update it.

**Comment by SchlegelS0208** [comment]
Yeah, we're using the NagAconda library for a nagios plugin called "check_influx" and it still works very well. :)
Thank you very much for merging this PR. ;)

Because of pypi.org:
Could you invite me as Maintainer in pypi.org? My Username is: SchlegelS0208

This way I could upload the new package version directly to pypi.org ( if you want to ).^^

Cheers,
Steven

**Comment by bonesmoses** [comment]
I've invited you as maintainer. Once you've successfully released it, I can hand it over. I haven't used Nagios in so long, I honestly shouldn't own this project anymore.

**Comment by SchlegelS0208** [comment]
> I've invited you as maintainer. Once you've successfully released it, I can hand it over. I haven't used Nagios in so long, I honestly shouldn't own this project anymore.

I uploaded the new package into pypi.org ;)

https://pypi.org/project/NagAconda/0.3.5/#history

I added your name and mail stuff into the description, so all guys know that you were the original author of this stuff.

The project points to my github repo, because you might drop the ownership.

I hope this is fine for you. :)

Cheers,
Steven

**Comment by bonesmoses** [comment]
Sounds good to me. Have a good one!

**Pull request merged**
